GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event 5",
  "description": "This is a new event 2",
  "date": "2018-01-01T00:00:00",
  "price": 200
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}


### 
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "New Event Updated",
  "description": "This is a new event UPDATED",
  "date": "2017-01-01T00:00:00",
  "price": 300
}

###
DELETE http://localhost:3000/events/{{eventId}}



### =============== SPOTS ===============


GET http://localhost:3000/events/{{eventId}}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A6"
}

###
@spotId = {{ createSpot.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}/spots/{{spotId}}


### 
PATCH http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
  "name": "A Updated"
}

###
DELETE http://localhost:3000/events/{{eventId}}/spots/{{spotId}}